// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//
// Anyone wanting to mod their own contracts should consult this link: http://forum.kerbalspaceprogram.com/threads/86588-Contract-Modding-Information-for-Mod-Authors
/*
 * 
Make a class extending ContractParameter
Override the following methods:
OnRegister()
OnUnregister()
OnLoad()
OnSave()
GetTitle()
GetHashString()
 */

using KSP;
using Contracts;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace IonKerbal
{
	[Serializable]
	public class IonResupplyStation : ContractParameter
	{
		//
		// Fields
		//
		[SerializeField]
		private IonResupplyStation.CompleteCondition failCondition;
		
		[SerializeField]
		private IonResupplyStation.CompleteCondition winCondition;
		
		[SerializeField]
		private string title = string.Empty;
		
		[SerializeField]
		private List<string> stationsToResupply = new List<string> ();
		
		//
		// Constructors
		//
		public IonResupplyStation (string title, IonResupplyStation.CompleteCondition winCondition = IonResupplyStation.CompleteCondition.All, IonResupplyStation.CompleteCondition failCondition = IonResupplyStation.CompleteCondition.All)
		{
			this.title = title;
			this.stationsToResupply = new List<string> ();
			this.failCondition = failCondition;
			this.winCondition = winCondition;
		}
		
		public IonResupplyStation ()
		{
		}
		
		//
		// Methods
		//

		
		protected override string GetTitle ()
		{
			return this.title;
		}
		

		protected override void OnLoad (ConfigNode node)
		{
		}
		
		protected override void OnRegister ()
		{
		}
		
		protected override void OnSave (ConfigNode node)
		{
		}
		
		protected override void OnUnregister ()
		{
		}

		public void SetTitle (string title)
		{
			this.title = title;
		}
		
		//
		// Nested Types
		//
		public enum CompleteCondition
		{
			All,
			Any
		}
	}
}


