// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using KSP;
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace IoncrossKerbal
{
	[KSPScenario(ScenarioCreationOptions.AddToAllGames, new GameScenes[]{GameScenes.FLIGHT,GameScenes.SPACECENTER})]
	public class IonLifeSupportScenario : ScenarioModule
	{
		public IonLifeSupportScenario ()
		{
		}

		public static IonLifeSupportScenario Instance;

		private bool __isLifeSupportEnabled = true;

		public bool _isLifeSupportEnabled
		{
			get
			{
				return __isLifeSupportEnabled;
			}
			set
			{
				__isLifeSupportEnabled = value;
			}
		}

		private bool _isThermalEnabled = true;

		public bool isThermalEnabled
		{
			get
			{
				return _isThermalEnabled;
			}
			set
			{
				_isThermalEnabled = value;
			}
		}

		public override void OnAwake ()
		{
			IonLifeSupportScenario.Instance = this;
		}

		public override void OnSave(ConfigNode node)
		{
			node.AddValue("_isLifeSupportEnabled", _isLifeSupportEnabled);
			node.AddValue("_isThermalEnabled", _isThermalEnabled);
		}

		public override void OnLoad(ConfigNode node)
		{
			if (node.HasValue("_isLifeSupportEnabled"))
				_isLifeSupportEnabled = bool.Parse (node.GetValue ("_isLifeSupportEnabled"));
			if (node.HasValue("_isThermalEnabled"))
				_isThermalEnabled = bool.Parse(node.GetValue("_isThermalEnabled"));
		}
	}
}

