// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using UnityEngine;
using UnityEngine.UI;
using KSP.UI;
using KSP.UI.Screens;

namespace IoncrossKerbal
{
	// Consulted Codepoet's CLS for guidance on using the stock toolbar system
	// Consulted RealChute & MechJeb2 for button implementation
	[KSPAddon(KSPAddon.Startup.SpaceCentre, false)]
	public class IonToolbar : UnityEngine.MonoBehaviour
	{
		private static Rect windowPosition = new Rect(0,0,360,480);
		private static GUIStyle windowStyle = null;

		#region Fields
		private GUISkin skins = HighLogic.Skin;
		private int id = Guid.NewGuid().GetHashCode();
		//private bool visible = false, showing = true;
		private Rect window = new Rect(), button = new Rect();
		private Texture2D buttonTexture = new Texture2D(1, 1);
		//private IonLifeSupportScenario ionLifeSupportScenario = IonLifeSupportScenario.Instance;
		#endregion
		
		#region Propreties
		private GUIStyle _buttonStyle = null;
		private GUIStyle buttonStyle
		{
			get
			{
				if (_buttonStyle == null)
				{
					_buttonStyle = new GUIStyle(skins.button);
					_buttonStyle.onNormal = _buttonStyle.hover;
				}
				return _buttonStyle;
			}
		}
		#endregion

		private ApplicationLauncherButton IonToolbarButton = null;
		private bool visible = false;

		public static IonToolbar Instance
		{
			get;
			private set;
		}

		public IonToolbar ()
		{
			if (Instance == null) 
			{
				Instance = this;
			}
		}
		public void Awake() 
		{
			// Set up the stock toolbar
			GameEvents.onGUIApplicationLauncherReady.Add(OnGUIAppLauncherReady);
			GameEvents.onGUIApplicationLauncherDestroyed.Add(OnGUIAppLauncherDestroyed);			
		}

		void OnGUIAppLauncherReady()
		{
			if (ApplicationLauncher.Ready)
			{
				this.IonToolbarButton = ApplicationLauncher.Instance.AddModApplication(onAppLaunchToggleOn,
				                                                                         onAppLaunchToggleOff,
				                                                                         DummyVoid,
				                                                                         DummyVoid,
				                                                                         DummyVoid,
				                                                                         DummyVoid,
				                                                                         ApplicationLauncher.AppScenes.SPACECENTER,
				                                                                         (Texture)GameDatabase.Instance.GetTexture("IoncrossCrewSupport/Assets/ion_icon_off", false));
			}
		}
		
		void OnGUIAppLauncherDestroyed()
		{
			if (this.IonToolbarButton != null)
			{
				ApplicationLauncher.Instance.RemoveModApplication(this.IonToolbarButton);
				this.IonToolbarButton = null;
			}
		}
		
		void onAppLaunchToggleOn()
		{
			this.IonToolbarButton.SetTexture((Texture)GameDatabase.Instance.GetTexture("IoncrossCrewSupport/Assets/ion_icon_on", false));
			this.visible = true;
		}

		void onAppLaunchToggleOff()
		{
			this.IonToolbarButton.SetTexture((Texture)GameDatabase.Instance.GetTexture("IoncrossCrewSupport/Assets/ion_icon_off", false));
			
			this.visible = false;
		}


		void DummyVoid()
		{
		}
		private void OnDraw()
		{
			if (this.visible)
			{
				//Set the GUI Skin
				//GUI.skin = HighLogic.Skin;
				
				windowPosition = GUILayout.Window(id, windowPosition, OnWindow, "Ioncross Settings", windowStyle,GUILayout.MinHeight(20),GUILayout.ExpandHeight(true));
			}
		}
		public void OnDestroy()
		{

			// Remove the stock toolbar button
			GameEvents.onGUIApplicationLauncherReady.Remove(OnGUIAppLauncherReady);
			if (this.IonToolbarButton != null)
				ApplicationLauncher.Instance.RemoveModApplication(IonToolbarButton);			
		}

		private void OnWindow(int windowID)
		{
			//GUILayout.BeginVertical ();
			//GUILayout.BeginHorizontal ();
			//GUILayout.Button(;
			//GUILayout.Label("Ioncross Crew Support: " 
			//GUILayout.Label ("Ioncross Stuff");
			IonLifeSupportScenario.Instance.IsLifeSupportEnabled = GUILayout.Toggle(IonLifeSupportScenario.Instance.IsLifeSupportEnabled, "Enable Ioncross Crew Support for this game save", skins.toggle);
			GUILayout.BeginHorizontal();
			GUILayout.FlexibleSpace();
			GUILayout.FlexibleSpace();
			GUILayout.EndHorizontal();

			GUI.DragWindow();
		}
	}
}

